import logging
from datetime import date

from core.llm import complete
from core.tracing import observe, update_span

logger = logging.getLogger(__name__)

SYSTEM_PROMPT = """\
You are a research analyst writing a daily intelligence brief.

Your reader is a smart, curious person who follows tech — but they are NOT a specialist. \
They want to understand what's actually happening, not just what the jargon says.

Your rules:
- Write like you are explaining to a smart friend over coffee, not writing an academic paper
- Every technical term must be explained in plain English the first time it appears
- No unexplained acronyms ever
- Be specific and concrete — vague summaries are useless
- If a paper has math, explain what the formula is actually DOING in one plain sentence
- Use Obsidian Markdown formatting exactly as instructed"""

USER_TEMPLATE = """\
Today is {date}. Research topic: **{topic}**

---
## COMMUNITY SIGNAL (what developers are talking about right now)
{signal}

---
## ACADEMIC PAPERS RETRIEVED
{papers_block}

---

Write a daily research brief using EXACTLY this structure:

# {topic} — {date}

## TL;DR
2-3 sentences maximum. What is the single most important thing happening in {topic} right now? \
Write it so someone could read this in 10 seconds and know if they need to read further. Plain English only.

## What the Community is Saying
> [!NOTE] Key Pulse
> (Write ONE sentence here capturing the strongest community sentiment)

Then 3-4 bullet points. For each: what is the community excited/worried about AND why does it matter. \
Do not just say what it is — say why people care.

## The Papers — What They Actually Do
For each paper write this exact format:

**[[Paper Title]]** — *First Author et al., Year*
- **In plain English:** (1 sentence — what problem does it solve and how, no jargon)
- **Why it matters:** (1 sentence — what changes if this works)
- **The key idea:** (2-3 sentences — explain the core contribution. If there is math, say what the equation is computing in words)

## Key Formulas
For each important equation from the papers:
```latex
(the formula)
```
> Plain English: (one sentence explaining what this formula is actually calculating)

If there are no notable formulas, write: *No key formulas in this batch.*

## What to Watch Next
3 specific bullet points. Name actual projects, researchers, conferences, or deadlines. \
Not generic advice — specific things to track in the next 2 weeks.

---
*Generated by Deep Signal Pipeline · {date}*"""


@observe(name="synthesizer")
def run(topic: str, signal: str, papers: list[dict], client, model: str, cfg: dict) -> str:
    today = date.today().isoformat()

    if not signal and not papers:
        logger.warning("Synthesizer: no signal and no papers — producing minimal brief")
        return f"# {topic} — {today}\n\n> [!WARNING]\n> No signal or papers retrieved for this topic today. Check Langfuse for details.\n"

    signal_budget = cfg.get("signal_char_budget", 12000)
    if signal and len(signal) > signal_budget:
        logger.info("Synthesizer: signal is %d chars, truncating to %d", len(signal), signal_budget)

    output, response = complete(
        client, model,
        USER_TEMPLATE.format(
            date=today,
            topic=topic,
            signal=signal[:signal_budget] if signal else "No community signal retrieved.",
            papers_block=_format_papers(papers),
        ),
        system=SYSTEM_PROMPT,
        max_tokens=16000,
        effort="high",
        name="write_brief",
    )

    update_span(
        input={"topic": topic, "paper_count": len(papers), "signal_length": len(signal)},
        output=output[:300],
    )

    logger.info(
        "Synthesizer: %d input tokens, %d output tokens",
        response.usage.input_tokens,
        response.usage.output_tokens,
    )
    return output


_CONTENT_LABELS = {"latex": "LaTeX source (body)", "pdf_text": "Extracted PDF text"}


def _format_papers(papers: list[dict]) -> str:
    if not papers:
        return "No papers retrieved."

    blocks = []
    for p in papers:
        content = p.get("content")
        if content:
            label = _CONTENT_LABELS.get(p.get("content_type"), "Full text")
            body = f"**Abstract:** {p.get('abstract', '')}\n\n**{label}:**\n{content}"
        else:
            body = f"**Abstract:** {p.get('abstract', 'No abstract available.')}"
        blocks.append(
            f"**Title:** {p['title']}\n"
            f"**Authors:** {', '.join(p['authors'])}\n"
            f"**ArXiv ID:** {p['id']}\n"
            f"**Published:** {p.get('published', 'unknown')}\n"
            f"{body}"
        )

    return "\n\n---\n\n".join(blocks)
